apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - pvc.yaml
  - vector-db.yaml

helmCharts:
  - name: immich
    repo: https://immich-app.github.io/immich-charts
    version: 0.1.3
    releaseName: immich
    namespace: immich
    valuesFile: values.yaml

