apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama-apps
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
  project: default
  source:
    repoURL: https://github.com/marcjazz/self-hosted.git
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

