# Use the version that matches your needs
image:
  repository: tensorchord/pgvecto-rs
  tag: pg14-v0.2.0

architecture: standalone # Use specific architecture if needed

global:
  security:
    allowInsecureImages: true

auth:
  existingSecret: immich-postgres-secret
  username: immich
  database: immich

primary:
  containerSecurityContext:
    readOnlyRootFilesystem: false
  initdb:
    user: postgres
    scripts:
      create-extensions.sql: |
        CREATE EXTENSION cube;
        CREATE EXTENSION earthdistance;
        CREATE EXTENSION vectors;

persistence:
  enabled: true
  size: 4Gi
  storageClass: standard

resources:
  requests:
    memory: 256Mi
    cpu: 100m
