# Use the version that matches your needs
image:
  repository: tensorchord/pgvecto-rs
  tag: pg14-v0.2.0

architecture: standalone # Use specific architecture if needed

global:
  security:
    allowInsecureImages: true
  postgresql:
    auth:
      existingSecret: postgres-secret

primary:
  postgresqlService: 'immich-postgres'
  containerSecurityContext:
    readOnlyRootFilesystem: false
  initdb:
    user: 'postgres'
    password:
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: postgresPassword
    scripts:
      create-extensions.sql: |
        CREATE EXTENSION cube;
        CREATE EXTENSION earthdistance;
        CREATE EXTENSION vectors;

persistence:
  enabled: true
  size: 4Gi
  storageClass: 'standard' # Adjust to your cluster's storage class

resources:
  requests:
    memory: 256Mi
    cpu: 100m
