name: Deploy Immich to Kubernetes

on:
  push:
    #    paths:
    #      - 'immich/**'
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate with Cluster
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Ensure Namespace Exists
        run: kubectl create namespace immich --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply PVC
        run: kubectl apply -f immich/k8s/01-library-pvc.yaml -n immich

      - name: Create Kubernetes Secret for PostgreSQL
        run: |
          kubectl create secret generic postgres-secret \
            --from-literal=username=${{ secrets.POSTGRES_USER }} \
            --from-literal=password=${{ secrets.POSTGRES_PASSWORD }} \
            --from-literal=database=${{ secrets.POSTGRES_DB }} \
            -n immich --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy PostgreSQL
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm upgrade --install immich-postgres bitnami/postgresql -f immich/k8s/02-postgres-values.yaml -n immich

      - name: Deploy Immich
        run: |
          helm repo add immich https://immich-app.github.io/immich-charts
          helm upgrade --install immich immich/immich -f immich/03-immich-values.yaml -n immich
